Set userimage filesystem format
Fixes:
[ 99% 10962/10965] Target system fs image: out/target/product/ibiza/obj/PACKAGING/systemimage_intermediates/system.img
FAILED: out/target/product/ibiza/obj/PACKAGING/systemimage_intermediates/system.img
/bin/bash -c "(mkdir -p out/target/product/ibiza/obj/PACKAGING/systemimage_intermediates/ out/target/product/ibiza/obj/PACKAGING/systemimage_intermediates && rm -rf out/target/product/ibiza/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"system_selinux_fc=out/target/product/ibiza/obj/ETC/file_contexts.bin_intermediates/file_contexts.bin\" >>  out/target/product/ibiza/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"building_system_image=true\" >>  out/target/product/ibiza/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"ext_mkuserimg=mkuserimg_mke2fs\" >>  out/target/product/ibiza/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"extfs_sparse_flag=-s\" >>  out/target/product/ibiza/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"erofs_sparse_flag=-s\" >>  out/target/product/ibiza/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"squashfs_sparse_flag=-s\" >>  out/target/product/ibiza/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"f2fs_sparse_flag=-S\" >>  out/target/product/ibiza/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"verity_disable=true\" >>  out/target/product/ibiza/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"recovery_as_boot=true\" >>  out/target/product/ibiza/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"root_dir=out/target/product/ibiza/root\" >>  out/target/product/ibiza/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"use_dynamic_partition_size=true\" >> out/target/product/ibiza/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"skip_fsck=true\" >>  out/target/product/ibiza/obj/PACKAGING/systemimage_intermediates/system_image_info.txt )&& (PATH=out/host/linux-x86/bin/:system/extras/ext4_utils/:\$PATH out/host/linux-x86/bin/build_image out/target/product/ibiza/system out/target/product/ibiza/obj/PACKAGING/systemimage_intermediates/system_image_info.txt out/target/product/ibiza/obj/PACKAGING/systemimage_intermediates/system.img out/target/product/ibiza/system || ( mkdir -p \${DIST_DIR}; cp out/target/product/ibiza/installed-files.txt \${DIST_DIR}/installed-files-rescued.txt; exit 1 ) )"
2024-05-15 19:18:43 - build_image.py - ERROR   : Failed to build out/target/product/ibiza/obj/PACKAGING/systemimage_intermediates/system.img from out/target/product/ibiza/system
Traceback (most recent call last):
  File "/aosp/android-12-1-0/out/host/linux-x86/bin/build_image/internal/stdlib/runpy.py", line 174, in _run_module_as_main
  File "/aosp/android-12-1-0/out/host/linux-x86/bin/build_image/internal/stdlib/runpy.py", line 72, in _run_code
  File "/aosp/android-12-1-0/out/host/linux-x86/bin/build_image/__main__.py", line 12, in <module>
  File "/aosp/android-12-1-0/out/host/linux-x86/bin/build_image/internal/stdlib/runpy.py", line 174, in _run_module_as_main
  File "/aosp/android-12-1-0/out/host/linux-x86/bin/build_image/internal/stdlib/runpy.py", line 72, in _run_code
  File "/aosp/android-12-1-0/out/host/linux-x86/bin/build_image/build_image.py", line 943, in <module>
  File "/aosp/android-12-1-0/out/host/linux-x86/bin/build_image/build_image.py", line 935, in main
  File "/aosp/android-12-1-0/out/host/linux-x86/bin/build_image/build_image.py", line 546, in BuildImage
  File "/aosp/android-12-1-0/out/host/linux-x86/bin/build_image/build_image.py", line 375, in BuildImageMkfs
__main__.BuildImageError: Error: unknown filesystem type:

[1] reads "fs_type" from prop_dict
[2] sets "fs_type" to INTERNAL_USERIMAGES_EXT_VARIANT
[3] shows that this value is set by TARGET_USERIMAGES_USE_EXT*

References:
[1] https://android.googlesource.com/platform/build/+/master/tools/releasetools/build_image.py#284
[2] https://android.googlesource.com/platform/build/+/a6860b3/core/Makefile#734
[3] https://cs.android.com/android/platform/superproject/+/android-12.1.0_r27:build/make/core/Makefile;l=1496-1507