Set OUT locations for SYSTEM_EXT, VENDOR, and PRODUCT partitions
Fixes:
[100% 213/213] build out/target/product/ibiza/obj/PACKAGING/check-all-partition-sizes_intermediates/check_all_partition_sizes.log
FAILED: out/target/product/ibiza/obj/PACKAGING/check-all-partition-sizes_intermediates/check_all_partition_sizes.log
/bin/bash -c "(mkdir -p out/target/product/ibiza/obj/PACKAGING/check-all-partition-sizes_intermediates/ ) && (rm -f  out/target/product/ibiza/obj/PACKAGING/check-all-partition-sizes_intermediates/misc_info.txt ) && (echo \"use_dynamic_partitions=true\" >>   out/target/product/ibiza/obj/PACKAGING/check-all-partition-sizes_intermediates/misc_info.txt ) && (echo \"lpmake=lpmake\" >>   out/target/product/ibiza/obj/PACKAGING/check-all-partition-sizes_intermediates/misc_info.txt ) && (echo \"build_super_partition=true\" >>   out/target/product/ibiza/obj/PACKAGING/check-all-partition-sizes_intermediates/misc_info.txt ) && (echo \"build_super_empty_partition=true\" >>   out/target/product/ibiza/obj/PACKAGING/check-all-partition-sizes_intermediates/misc_info.txt ) && (echo \"super_metadata_device=super\" >>   out/target/product/ibiza/obj/PACKAGING/check-all-partition-sizes_intermediates/misc_info.txt ) && (echo \"super_block_devices=super\" >>   out/target/product/ibiza/obj/PACKAGING/check-all-partition-sizes_intermediates/misc_info.txt ) && (echo\"super_super_device_size=12884901888\" >>   out/target/product/ibiza/obj/PACKAGING/check-all-partition-sizes_intermediates/misc_info.txt ) && (echo \"dynamic_partition_list=system system_ext product\" >>   out/target/product/ibiza/obj/PACKAGING/check-all-partition-sizes_intermediates/misc_info.txt ) && (echo \"super_partition_groups=mot_dynamic_partitions\" >>   out/target/product/ibiza/obj/PACKAGING/check-all-partition-sizes_intermediates/misc_info.txt ) && (echo \"super_mot_dynamic_partitions_group_size=6438256640\" >>   out/target/product/ibiza/obj/PACKAGING/check-all-partition-sizes_intermediates/misc_info.txt;  echo \"super_mot_dynamic_partitions_partition_list=system system_ext product\" >>   out/target/product/ibiza/obj/PACKAGING/check-all-partition-sizes_intermediates/misc_info.txt ) && (echo \"super_partition_size=12884901888\" >>   out/target/product/ibiza/obj/PACKAGING/check-all-partition-sizes_intermediates/misc_info.txt ) && (echo \"ab_update=true\" >>   out/target/product/ibiza/obj/PACKAGING/check-all-partition-sizes_intermediates/misc_info.txt ) && (echo \"system_image=\"out/target/product/ibiza/system.img >>  out/target/product/ibiza/obj/PACKAGING/check-all-partition-sizes_intermediates/misc_info.txt;  echo \"system_ext_image=\">>  out/target/product/ibiza/obj/PACKAGING/check-all-partition-sizes_intermediates/misc_info.txt;  echo \"vendor_image=\" >>  out/target/product/ibiza/obj/PACKAGING/check-all-partition-sizes_intermediates/misc_info.txt;  echo \"product_image=\" >>  out/target/product/ibiza/obj/PACKAGING/check-all-partition-sizes_intermediates/misc_info.txt ) && (out/host/linux-x86/bin/check_partition_sizes --logfile  out/target/product/ibiza/obj/PACKAGING/check-all-partition-sizes_intermediates/check_all_partition_sizes.log  out/target/product/ibiza/obj/PACKAGING/check-all-partition-sizes_intermediates/misc_info.txt )"
Traceback (most recent call last):
  File "/aosp/android-12-1-0/out/host/linux-x86/bin/check_partition_sizes/internal/stdlib/runpy.py", line 174, in _run_module_as_main
  File "/aosp/android-12-1-0/out/host/linux-x86/bin/check_partition_sizes/internal/stdlib/runpy.py", line 72, in _run_code
  File "/aosp/android-12-1-0/out/host/linux-x86/bin/check_partition_sizes/__main__.py", line 12, in <module>
  File "/aosp/android-12-1-0/out/host/linux-x86/bin/check_partition_sizes/internal/stdlib/runpy.py", line 174, in _run_module_as_main
  File "/aosp/android-12-1-0/out/host/linux-x86/bin/check_partition_sizes/internal/stdlib/runpy.py", line 72, in _run_code
  File "/aosp/android-12-1-0/out/host/linux-x86/bin/check_partition_sizes/check_partition_sizes.py", line 302, in <module>
  File "/aosp/android-12-1-0/out/host/linux-x86/bin/check_partition_sizes/check_partition_sizes.py", line 296, in main
  File "/aosp/android-12-1-0/out/host/linux-x86/bin/check_partition_sizes/check_partition_sizes.py", line 284, in CheckPartitionSizes
  File "/aosp/android-12-1-0/out/host/linux-x86/bin/check_partition_sizes/check_partition_sizes.py", line 276, in Run
  File "/aosp/android-12-1-0/out/host/linux-x86/bin/check_partition_sizes/check_partition_sizes.py", line 234, in _CheckAllPartitionSizes
  File "/aosp/android-12-1-0/out/host/linux-x86/bin/check_partition_sizes/check_partition_sizes.py", line 164, in _CheckSumOfPartitionSizes
  File "/aosp/android-12-1-0/out/host/linux-x86/bin/check_partition_sizes/check_partition_sizes.py", line 139, in _ReadSizeOfPartition
  File "/aosp/android-12-1-0/out/host/linux-x86/bin/check_partition_sizes/sparse_img.py", line 364, in GetImagePartitionSize
  File "/aosp/android-12-1-0/out/host/linux-x86/bin/check_partition_sizes/sparse_img.py", line 46, in __init__
IOError: [Errno 2] No such file or directory: ''

Otherwise, these partitions are built into the system image:
19:45:11 Removed empty directory (may no longer be installed?):  out/target/product/ibiza/system/product/app/Browser2
19:45:11 Removed file that is no longer installed:  out/target/product/ibiza/system/system_ext/priv-app/WallpaperCropper/WallpaperCropper.apk
19:45:11 Removed file that is no longer installed:  out/target/product/ibiza/system/vendor/bin/awk

References:
https://android.googlesource.com/platform/build.git/+/brillo-m10-dev/core/envsetup.mk#116